#!/bin/bash

#Pledge in Lovelace
PLEDGE=1000000000 # 1000 ADA
#Pool cost in Lovelace
COST=340000000 # 340 ADA

MARGIN=0.05 # 5%

RELAY_PORT=3001

# domain name of your relay, e.g relay.stakepool.com
RELAY_DOMAIN=""

# URL link to meta.json, e.g 
META_URL=""

WALLET_PATH="$HOME/priv/wallet/$1"
POOL_PATH="$HOME/priv/pool/$2"
TMP="/opt/cardano/tmp"



if [ -f "$POOL_PATH/$1.node.skey.gpg" ]; then
   echo "Cold keys of $2 are encrypted!"
   exit
fi

if [ -f "$WALLET_PATH/$1.payment.skey.gpg" ]; then
   echo "$1 Wallet is encrypted!"
   exit
fi



cardano-cli shelley query protocol-parameters \
    --mainnet \
    --out-file "$TMP/params.json" \
    --cardano-mode


cardano-cli shelley stake-pool metadata-hash --pool-metadata-file "$POOL_PATH/poolmeta.json" > "$POOL_PATH/poolmetaHash.txt"

minPoolCost=$(cat "$TMP/params.json" | jq -r .minPoolCost)
echo minPoolCost: "${minPoolCost}"

cardano-cli shelley stake-pool registration-certificate \
    --cold-verification-key-file "$POOL_PATH/$2.node.vkey" \
    --vrf-verification-key-file "$POOL_PATH/$2.vrf.vkey" \
    --pool-pledge "$PLEDGE" \
    --pool-cost "$COST" \
    --pool-margin "$MARGIN" \
    --pool-reward-account-verification-key-file "$WALLET_PATH/$1.stake.vkey" \
    --pool-owner-stake-verification-key-file "$WALLET_PATH/$1.stake.vkey" \
    --mainnet \
    --single-host-pool-relay "$RELAY_DOMAIN" \
    --pool-relay-port $RELAY_PORT \
    --metadata-url "$META_URL" \
    --metadata-hash $(cat "$POOL_PATH/poolmetaHash.txt") \
    --out-file "$POOL_PATH/$2.pool.cert"

cardano-cli shelley stake-address delegation-certificate \
    --staking-verification-key-file "$WALLET_PATH/$1.stake.vkey" \
    --cold-verification-key-file "$POOL_PATH/$2.node.vkey" \
    --out-file "$WALLET_PATH/$1.deleg.cert"


currentSlot=$(cardano-cli shelley query tip --mainnet | jq -r '.slotNo')
echo "Current Slot: $currentSlot"

cardano-cli shelley query utxo \
    --address $(cat "$WALLET_PATH/$1.payment.addr") \
    --mainnet \
    --cardano-mode > "$TMP/fullUtxo.out"

tail -n +3 "$TMP/fullUtxo.out" | sort -k3 -nr > "$TMP/balance.out"

cat "$TMP/balance.out"

tx_in=""
total_balance=0
while read -r utxo; do
    in_addr=$(awk '{ print $1 }' <<< "${utxo}")
    idx=$(awk '{ print $2 }' <<< "${utxo}")
    utxo_balance=$(awk '{ print $3 }' <<< "${utxo}")
    total_balance=$((${total_balance}+${utxo_balance}))
    echo TxHash: ${in_addr}#${idx}
    echo ADA: ${utxo_balance}
    tx_in="${tx_in} --tx-in ${in_addr}#${idx}"
done < "$TMP/balance.out"
txcnt=$(cat "$TMP/balance.out" | wc -l)
echo "Total ADA balance of $1 Wallet": ${total_balance}
echo Number of UTXOs: ${txcnt}


poolDeposit=$(cat "$TMP/params.json" | jq -r '.poolDeposit')
echo poolDeposit: "$poolDeposit"


cardano-cli shelley transaction build-raw \
    ${tx_in} \
    --tx-out $(cat "$WALLET_PATH/$1.payment.addr")+$(( ${total_balance} - ${poolDeposit}))  \
    --ttl $(( ${currentSlot} + 10000)) \
    --fee 0 \
    --certificate-file "$POOL_PATH/$2.pool.cert" \
    --certificate-file "$WALLET_PATH/$1.deleg.cert" \
    --out-file "$TMP/tx.tmp"


fee=$(cardano-cli shelley transaction calculate-min-fee \
    --tx-body-file "$TMP/tx.tmp" \
    --tx-in-count ${txcnt} \
    --tx-out-count 1 \
    --mainnet \
    --witness-count 3 \
    --byron-witness-count 0 \
    --protocol-params-file "$TMP/params.json" | awk '{ print $1 }')
echo fee: $fee


txOut=$((${total_balance}-${fee}))
echo txOut: "${txOut}"

cardano-cli shelley transaction build-raw \
    ${tx_in} \
    --tx-out $(cat "$WALLET_PATH/$1.payment.addr")+${txOut} \
    --ttl $(( ${currentSlot} + 10000)) \
    --fee ${fee} \
    --certificate-file "$POOL_PATH/$2.pool.cert" \
    --certificate-file "$WALLET_PATH/$1.deleg.cert" \
    --out-file "$TMP/tx.raw"

cardano-cli shelley transaction sign \
    --tx-body-file "$TMP/tx.raw" \
    --signing-key-file "$WALLET_PATH/$1.payment.skey" \
    --signing-key-file "$POOL_PATH/$2.node.skey" \
    --signing-key-file "$WALLET_PATH/$1.stake.skey" \
    --mainnet \
    --out-file "$TMP/tx.signed"

cardano-cli shelley transaction submit \
    --tx-file "$TMP/tx.signed" \
    --mainnet \
    --cardano-mode

cardano-cli shelley stake-pool id --verification-key-file "$POOL_PATH/$2.node.vkey" > "$POOL_PATH/$2.id.txt"


echo "$2 modified with new Pledge: $PLEDGE, Cost: $COST, Margin: $MARGIN"


