#!/bin/bash

WALLET_PATH="$HOME/priv/wallet/$1"
TMP="/opt/cardano/tmp"

cardano-cli shelley query protocol-parameters \
    --mainnet \
    --out-file "$TMP/params.json" \
    --cardano-mode

cardano-cli shelley stake-address registration-certificate \
    --staking-verification-key-file "$WALLET_PATH/$1.stake.vkey" \
    --out-file "$WALLET_PATH/$1.stake.cert"


currentSlot=$(cardano-cli shelley query tip --mainnet | jq -r '.slotNo')
echo "Current Slot: $currentSlot"


cardano-cli shelley query utxo \
    --address $(cat "$WALLET_PATH/$1.payment.addr") \
    --mainnet \
    --cardano-mode > "$TMP/fullUtxo.out"

tail -n +3 "$TMP/fullUtxo.out" | sort -k3 -nr > "$TMP/balance.out"

cat "$TMP/balance.out"

tx_in=""
total_balance=0
while read -r utxo; do
    in_addr=$(awk '{ print $1 }' <<< "${utxo}")
    idx=$(awk '{ print $2 }' <<< "${utxo}")
    utxo_balance=$(awk '{ print $3 }' <<< "${utxo}")
    total_balance=$((${total_balance}+${utxo_balance}))
    echo TxHash: ${in_addr}#${idx}
    echo ADA: ${utxo_balance}
    tx_in="${tx_in} --tx-in ${in_addr}#${idx}"
done < "$TMP/balance.out"
txcnt=$(cat "$TMP/balance.out" | wc -l)
echo "Total ADA balance of $1 Wallet": ${total_balance}
echo Number of UTXOs: ${txcnt}


keyDeposit=$(cat "$TMP/params.json" | jq -r '.keyDeposit')
echo "keyDeposit: $keyDeposit"

cardano-cli shelley transaction build-raw \
    ${tx_in} \
    --tx-out $(cat "$WALLET_PATH/$1.payment.addr")+0 \
    --ttl $(( ${currentSlot} + 10000)) \
    --fee 0 \
    --out-file "$TMP/tx.tmp" \
    --certificate "$WALLET_PATH/$1.stake.cert"


fee=$(cardano-cli shelley transaction calculate-min-fee \
    --tx-body-file "$TMP/tx.tmp" \
    --tx-in-count ${txcnt} \
    --tx-out-count 1 \
    --mainnet \
    --witness-count 2 \
    --byron-witness-count 0 \
    --protocol-params-file "$TMP/params.json" | awk '{ print $1 }')
echo fee: "$fee"


txOut=$((${total_balance}-${keyDeposit}-${fee}))
echo "Change Output: ${txOut}"

cardano-cli shelley transaction build-raw \
    ${tx_in} \
    --tx-out $(cat "$WALLET_PATH/$1.payment.addr")+${txOut} \
    --ttl $(( ${currentSlot} + 10000)) \
    --fee ${fee} \
    --certificate-file "$WALLET_PATH/$1.stake.cert" \
    --out-file "$TMP/tx.raw"

cardano-cli shelley transaction sign \
    --tx-body-file "$TMP/tx.raw" \
    --signing-key-file "$WALLET_PATH/$1.payment.skey" \
    --signing-key-file "$WALLET_PATH/$1.stake.skey" \
    --mainnet \
    --out-file "$TMP/tx.signed"

cardano-cli shelley transaction submit \
    --tx-file "$TMP/tx.signed" \
    --mainnet \
    --cardano-mode

echo "Registered $1 Stake Address!"


