#!/bin/bash

WALLET_PATH="$HOME/priv/wallet/$1"
TMP="/opt/cardano/tmp"


if [ -f "$WALLET_PATH/$1.payment.skey.gpg" ]; then
   echo "$1 Wallet is encrypted!"
   exit
fi


cardano-cli shelley query protocol-parameters \
    --mainnet \
    --out-file "$TMP/params.json" \
    --cardano-mode

currentSlot=$(cardano-cli shelley query tip --mainnet | jq -r '.slotNo')
echo "Current Slot: $currentSlot"


cardano-cli shelley query utxo \
    --address $(cat "$WALLET_PATH/$1.payment.addr") \
    --mainnet \
    --cardano-mode > "$TMP/fullUtxo.out"

tail -n +3 "$TMP/fullUtxo.out" | sort -k3 -nr > "$TMP/balance.out"

cat "$TMP/balance.out"

tx_in=""
total_balance=0
while read -r utxo; do
    in_addr=$(awk '{ print $1 }' <<< "${utxo}")
    idx=$(awk '{ print $2 }' <<< "${utxo}")
    utxo_balance=$(awk '{ print $3 }' <<< "${utxo}")
    total_balance=$((${total_balance}+${utxo_balance}))
    echo TxHash: ${in_addr}#${idx}
    echo ADA: ${utxo_balance}
    tx_in="${tx_in} --tx-in ${in_addr}#${idx}"
done < "$TMP/balance.out"
txcnt=$(cat "$TMP/balance.out" | wc -l)
echo "Total ADA balance of $1 Wallet": ${total_balance}
echo Number of UTXOs: ${txcnt}


if [[ "$2" != "all" ]]; then

cardano-cli shelley transaction build-raw \
    ${tx_in} \
    --tx-out $(cat "$WALLET_PATH/$1.payment.addr")+0 \
    --tx-out "$3+0" \
    --ttl $(( ${currentSlot} + 10000)) \
    --fee 0 \
    --out-file "$TMP/tx.tmp" \


fee=$(cardano-cli shelley transaction calculate-min-fee \
    --tx-body-file "$TMP/tx.tmp" \
    --tx-in-count ${txcnt} \
    --tx-out-count 2 \
    --mainnet \
    --witness-count 1 \
    --byron-witness-count 0 \
    --protocol-params-file "$TMP/params.json" | awk '{ print $1 }')
echo fee: "$fee"


txOut=$((${total_balance}-$2-${fee}))
echo "Change Output: ${txOut}"

cardano-cli shelley transaction build-raw \
    ${tx_in} \
    --tx-out $(cat "$WALLET_PATH/$1.payment.addr")+${txOut} \
    --tx-out "$3+$2" \
    --ttl $(( ${currentSlot} + 10000)) \
    --fee ${fee} \
    --out-file "$TMP/tx.raw"

cardano-cli shelley transaction sign \
    --tx-body-file "$TMP/tx.raw" \
    --signing-key-file "$WALLET_PATH/$1.payment.skey" \
    --mainnet \
    --out-file "$TMP/tx.signed"

cardano-cli shelley transaction submit \
    --tx-file "$TMP/tx.signed" \
    --mainnet \
    --cardano-mode

echo "Sent $2 Lovelace to $3!"

else

cardano-cli shelley transaction build-raw \
    ${tx_in} \
    --tx-out "$3+0" \
    --ttl $(( ${currentSlot} + 10000)) \
    --fee 0 \
    --out-file "$TMP/tx.tmp" \


fee=$(cardano-cli shelley transaction calculate-min-fee \
    --tx-body-file "$TMP/tx.tmp" \
    --tx-in-count ${txcnt} \
    --tx-out-count 1 \
    --mainnet \
    --witness-count 1 \
    --byron-witness-count 0 \
    --protocol-params-file "$TMP/params.json" | awk '{ print $1 }')
echo fee: "$fee"


txOut=$((${total_balance}-${fee}))
echo "Change Output: ${txOut}"

cardano-cli shelley transaction build-raw \
    ${tx_in} \
    --tx-out "$3+$txOut" \
    --ttl $(( ${currentSlot} + 10000)) \
    --fee ${fee} \
    --out-file "$TMP/tx.raw"

cardano-cli shelley transaction sign \
    --tx-body-file "$TMP/tx.raw" \
    --signing-key-file "$WALLET_PATH/$1.payment.skey" \
    --mainnet \
    --out-file "$TMP/tx.signed"

cardano-cli shelley transaction submit \
    --tx-file "$TMP/tx.signed" \
    --mainnet \
    --cardano-mode


echo "Sent $txOut Lovelace to $3"

fi
