#!/bin/bash

TMP="/opt/cardano/tmp"
POOL_PATH="$HOME/priv/pool/$1"


if [ -f "$POOL_PATH/$1.node.skey.gpg" ]; then
   echo "Cold keys of $1 are encrypted!"
   exit
fi


slotNo=$(cardano-cli shelley query tip --mainnet | jq -r '.slotNo')
slotsPerKESPeriod=$(cat $RELAY/files/mainnet-shelley-genesis.json | jq -r '.slotsPerKESPeriod')
kesPeriod=$((${slotNo} / ${slotsPerKESPeriod}))

cardano-cli shelley node issue-op-cert \
    --kes-verification-key-file "$POOL_PATH/$1.kes.vkey" \
    --cold-signing-key-file "$POOL_PATH/$1.node.skey" \
    --operational-certificate-issue-counter "$POOL_PATH/$1.node.counter" \
    --kes-period ${kesPeriod} \
    --out-file "$POOL_PATH/$1.node.cert"

echo "Restart your core node with the new keys!"
