#!/bin/bash

WALLET_PATH="$HOME/priv/wallet/$1"
TMP="/opt/cardano/tmp"


cardano-cli shelley query protocol-parameters \
    --mainnet \
    --out-file "$TMP/params.json" \
    --cardano-mode


cardano-cli shelley query utxo \
    --address $(cat "$WALLET_PATH/$1.payment.addr") \
    --mainnet \
    --cardano-mode > "$TMP/fullUtxo.out"

tail -n +3 "$TMP/fullUtxo.out" | sort -k3 -nr > "$TMP/balance.out"


tx_in=""
total_balance=0
while read -r utxo; do
    in_addr=$(awk '{ print $1 }' <<< "${utxo}")
    idx=$(awk '{ print $2 }' <<< "${utxo}")
    utxo_balance=$(awk '{ print $3 }' <<< "${utxo}")
    total_balance=$((${total_balance}+${utxo_balance}))
    tx_in="${tx_in} --tx-in ${in_addr}#${idx}"
done < "$TMP/balance.out"
txcnt=$(cat "$TMP/balance.out" | wc -l)
BALANCE=`echo "scale=6; ${total_balance}*10^-6" | bc -l`
STAKE_ADDR=$(cat "$WALLET_PATH/$1.stake.addr")
REWARD=$(cardano-cli shelley query stake-address-info --address "$STAKE_ADDR" --mainnet | jq -r '.[]' | jq -r '.rewardAccountBalance')
REWARD=`echo "scale=6; ${REWARD}*10^-6" | bc -l`

STATUS=""
if [ -f "$WALLET_PATH/$1.payment.skey" ]; then
    STATUS="decrypted"
else 
    STATUS="encrypted"
fi

echo
echo "$1 Wallet   ($STATUS)"
echo
echo "Address: $(cat $WALLET_PATH/$1.payment.addr)"
echo "Balance: $BALANCE ADA"
echo "Reward: $REWARD ADA"
echo
